ALTER TABLE devices ADD COLUMN IF NOT EXISTS imei VARCHAR(50);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS sim_number VARCHAR(50);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS is_rooted BOOLEAN DEFAULT false;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS lost_mode BOOLEAN DEFAULT false;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS lost_mode_message TEXT;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS data_usage_bytes BIGINT DEFAULT 0;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS wifi_ssid VARCHAR(255);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS compliance_status VARCHAR(20) DEFAULT 'compliant';
